""""" HE: VIMRC

"""" PLUGIN MANAGER

""" Vim-plug BEGIN
call plug#begin('~/.vim/plugged')

""" PLUGIN LIST
" inhance netrw
Plug 'tpope/vim-vinegar'
" filetree explorer
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
" git status flags on NerdTree
" Plug 'Xuyuanp/nerdtree-git-plugin'
" git wrapper
Plug 'tpope/vim-fugitive'
" show a git diff in the 'gutter'
Plug 'airblade/vim-gitgutter'
" async syntax checker
Plug 'w0rp/ale'
" fuzzy file finder
Plug 'kien/ctrlp.vim'
" fuzzy file finder
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
" use <tab> for insert mode completions
Plug 'ervandew/supertab'
" comment functions
Plug 'scrooloose/nerdcommenter'
" simple mappings for quoting/parenthesizing
Plug 'tpope/vim-surround'
" remap . in a way that plugins can tap into it
Plug 'tpope/vim-repeat'
" vim motion on speed
Plug 'easymotion/vim-easymotion'
" insert or delete brackets, parens, quotes in pair
Plug 'jiangmiao/auto-pairs'
" molokai colorscheme
Plug 'tomasr/molokai'
" oceanic-next colorscheme
Plug 'mhartington/oceanic-next'
" monokai inspired colorscheme
Plug 'patstockwell/vim-monokai-tasty'
" vim plugin for ack
Plug 'mileszs/ack.vim'
" vim plugin for the silver searcher
Plug 'rking/ag.vim'
" expand html abbreviations
Plug 'mattn/emmet-vim'
" add indent guides
Plug 'nathanaelkane/vim-indent-guides'
" add status/tabline
Plug 'bling/vim-airline'
" themes for airline
Plug 'vim-airline/vim-airline-themes'
" a collection of language packs for Vim
Plug 'sheerun/vim-polyglot'
" expand javascript support
Plug 'pangloss/vim-javascript'
" react jsx syntax highlighting and indenting
Plug 'mxw/vim-jsx'
" better json for vim
Plug 'elzr/vim-json'
" yet Another JavaScript Syntax file for Vim
Plug 'othree/yajs.vim'
" syntax for javascript libraries
Plug 'othree/javascript-libraries-syntax.vim'
" tools for developing with Node.js in vim
Plug 'moll/vim-node'
"Plug 'maxmellon/vim-jsx-pretty'
"Plug 'chemzqm/vim-jsx-improve' "disabled vim-javascript to enable this
" css3 syntax
Plug 'hail2u/vim-css3-syntax'
" html5 omnicomplete and syntax
Plug 'othree/html5.vim', {'for': 'html'}
" qml syntax highlighting
Plug 'peterhoeg/vim-qml', {'for': 'qml'}
" qt->qrc syntax highlighting
Plug 'edtsft/vim-qrc', {'for': 'qrc'}
" comply with pep8 in python indentation
Plug 'Vimjas/vim-python-pep8-indent', {'for': 'py'}
" snippets engine for vim
Plug 'SirVer/ultisnips'
" snippets
Plug 'honza/vim-snippets'
" react code snippets
Plug 'epilande/vim-react-snippets'
" ledger filetype for vim
Plug 'ledger/vim-ledger', {'for': ['ledger', 'ldg', 'dat']}
" vim interface for taskwarrior
Plug 'blindFS/vim-taskwarrior'
" up to date php syntax for vim
Plug 'StanAngeloff/php.vim', {'for': 'php'}
" better indent HTML sections in PHP files
Plug 'captbaritone/better-indent-support-for-php-with-html', {'for': 'php'}
" pug template engine syntax highlighting and indention
Plug 'digitaltoad/vim-pug'
" open a list of most recently used files
Plug 'yegappan/mru'
" sublime text style multiple selections for Vim
Plug 'terryma/vim-multiple-cursors'
" dark powered asynchronous completion framework for neovim/Vim8
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
" LSP support for vim and neovim
Plug 'autozimu/LanguageClient-neovim', {
      \ 'branch': 'next',
      \ 'do': 'bash install.sh',
      \ }
" Prettier
Plug 'prettier/vim-prettier', {
      \ 'do': 'yarn install',
      \ 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html'] }
" no-hassle Vim sessions
Plug 'tpope/vim-obsession'
" tern-based JavaScript editing support
"  (requires npm install inside .vim/plugged/tern_for_vim)
"Plug 'ternjs/tern_for_vim', { 'for': ['javascript', 'javascript.jsx'] }
" deoplete.nvim source for javascript
"Plug 'carlitux/deoplete-ternjs', { 'for': ['javascript', 'javascript.jsx'] }
" completion function for function parameters
Plug 'othree/jspc.vim', { 'for': ['javascript', 'javascript.jsx'] }
" deoplete.nvim source for Python
Plug 'zchee/deoplete-jedi', { 'for': 'python' }
" omni-completion plugin for Java
Plug 'artur-shaik/vim-javacomplete2', { 'for': 'java' }
" syntax source for neocomplete/deoplete/ncm
Plug 'Shougo/neco-syntax'
" completion of words in adjacent tmux panes
Plug 'wellle/tmux-complete.vim'
" navigate seamlessly between vim and tmux splits
Plug 'christoomey/vim-tmux-navigator'
" easily interact with tmux from vim
Plug 'benmills/vimux'
" syntax checker
"Plug 'scrooloose/syntastic'
" tab completion
"Plug 'Valloric/YouCompleteMe'
" updates tags files automatically when saving
"Plug 'craigemery/vim-autotag'

""" Vim-plug END
call plug#end()


"""" USER

""" GENERAL
"" Basic
syntax on
syntax enable
set nocompatible	" be iMproved
filetype on
set modelines=0   "CVE-2007-2438
set backspace=2   "more powerful backspacing
" don't write backup file if vim is being called by "crontab -e"
autocmd BufWrite /private/tmp/crontab.* set nowritebackup
" don't write backup file if vim is being called by "chpass"
autocmd BufWrite /private/etc/pw.* set nowritebackup
set encoding=utf8
" disable automatic commenting
autocmd FileType * set fo-=c fo-=r fo-=o
"" Netrw
let g:netrw_winsize = 30
let g:netrw_liststyle=3
autocmd FileType netrw setl bufhidden=wipe
"" Completion
set complete=.,b,u,]
set completeopt=longest,menuone
"" Tabing
set expandtab
set tabstop=2
set shiftwidth=2
" python
autocmd FileType python setlocal sw=4 ts=4
"" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase
"" Snippets
set rtp+=./custom-snippets/
"" Visuals
" for vim 7
set t_Co=256
" for vim 8
let &t_8f = "\<Esc>[38:2:%lu:%lu:%lum"
let &t_8b = "\<Esc>[48:2:%lu:%lu:%lum"
if (has("termguicolors"))
  set termguicolors
endif
" theme
let g:vim_monokai_tasty_italic = 1
colorscheme vim-monokai-tasty
set background=dark
set mouse=a
set number
set relativenumber
set cursorline
" highlight number on cursorline
hi LineNr term=bold ctermfg=237 ctermbg=NONE gui=bold guifg=#3a3a3a guibg=NONE
hi clear CursorLine
augroup CLClear
  autocmd! ColorScheme * hi clear CursorLine
augroup END
hi CursorLineNr term=bold ctermfg=Yellow gui=bold guifg=Yellow

""" MAPPINGS
"" General
" leader
nnoremap <space> <nop>
let mapleader = "\<space>"
" local leader
let maplocalleader = "\\"
" better escape
inoremap jk <esc>
" apply mapping
nnoremap Q @q
vnoremap Q :norm @q<CR>
" better completion (uncomment if not using a plugin)
"inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
"inoremap <expr><CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
" better movements between splits
noremap <leader>j <C-W>j
noremap <leader>jj <C-W>j
noremap <leader>k <C-W>k
noremap <leader>kk <C-W>k
noremap <leader>h <C-W>h
noremap <leader>hh <C-W>h
noremap <leader>l <C-W>l
noremap <leader>ll <C-W>l
" split resize
nnoremap <leader>= <C-W>=
nnoremap <leader>> <C-W>>
nnoremap <leader>< <C-W><
nnoremap <leader>+ <C-W>+
nnoremap <leader>- <C-W>-
" quick open
nnoremap <leader>ss :vsplit<CR>
nnoremap <leader>sv :vsplit<CR>
nnoremap <leader>sh :split<CR>
nnoremap <leader>gf :vertical wincmd f<CR>
nnoremap <leader>nt :NERDTree<CR>
nnoremap <leader>ak :Ack<space>
nnoremap <leader>aa :Ag<space>
nnoremap <leader>ag :Ag<space>
" tabs
nnoremap <leader>tn :tabnew<CR>
nnoremap <leader>tc :tabclose<CR>
" remove highlight
nnoremap <leader>nh :nohlsearch<CR>
" toggle preview window
nnoremap <leader>tpr :call TogglePreview()<CR>
" toggle relative numbers
nnoremap <leader>trn :call ToggleRelativeNumbers()<CR>
" strip trailing whitespaces
nnoremap <leader>stw :call StripTrailingWhitespaces()<CR>
" buffers
nnoremap <leader>bl :bn<CR>
nnoremap <leader>Bl :bn!<CR>
nnoremap <leader>bn :bn<CR>
nnoremap <leader>Bn :bn!<CR>
nnoremap <leader>bh :bp<CR>
nnoremap <leader>Bh :bp!<CR>
nnoremap <leader>bp :bp<CR>
nnoremap <leader>Bp :bp!<CR>
nnoremap <leader>bs :buffers<CR>
nnoremap <leader>bb :buffers<CR>:buffer<Space>
nnoremap <leader>Bb :buffers<CR>:buffer!<Space>
nnoremap <leader>bd :bd<CR>
nnoremap <leader>Bd :bd!<CR>
nnoremap <leader>ba :1,1000 bd!<CR>
nnoremap <leader>bq :bp <BAR> bd #<CR>
nnoremap <leader>Bq :bp! <BAR> bd! #<CR>
" edit new buffer
nnoremap <leader>en :enew<CR>
nnoremap <leader>En :enew!<CR>
nnoremap <leader>ef :e<Space>
nnoremap <leader>ee :e<Space>
" edit/save vimrc
nnoremap <leader>ve :edit $MYVIMRC<CR>
nnoremap <leader>vrc :edit $HOME/.vimrc<CR>
nnoremap <leader>Ve :edit! $MYVIMRC<CR>
nnoremap <leader>Vrc :edit $HOME/.vimrc<CR>
nnoremap <leader>vs :source $MYVIMRC<CR>:nohlsearch<CR>
" quit a file
nnoremap <leader>q :q<CR>
nnoremap <leader>Q :q!<CR>
" save a file
nnoremap <leader>w :w<CR>
nnoremap <leader>ww :w<CR>
inoremap <C-S> <Esc>:w<cr>i
" save then quit a file
nnoremap <leader>wq :wq<CR>
nnoremap <leader>Wq :wq!<CR>
" open mru vim
nnoremap <leader>fr :MRU<CR>
" add line without changing mode or position
nnoremap <leader>o m`o<Esc>``
nnoremap <leader>O m`O<Esc>``
" yank text to the OS X clipboard
noremap <leader>y "*y
noremap <leader>yy "*Y
" preserve indentation while pasting text from the OS X clipboard
noremap <leader>p :set paste<CR>:put  *<CR>:set nopaste<CR>
" preserve visual selection after indenting
vmap > >gv
vmap < <gv
"" Ale mappings
" ale error navigation
nnoremap <leader>erp :ALEPreviousWrap<CR>
nnoremap <leader>ern :ALENextWrap<CR>
"" Fzf mappings
nnoremap <leader><tab> :Files<CR>
nnoremap <leader>fzf :Files<CR>
nnoremap <leader>fzb :Buffers<CR>
nnoremap <leader>fzc :Commits<CR>
"" Fugitive mappings
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gw :Gwrite<CR>
nnoremap <leader>gr :Gread<CR>
nnoremap <leader>gc :Gcommit<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>gmv :Gmove<space>
nnoremap <leader>gb :Git branch<Space>
nnoremap <leader>go :Git checkout<Space>
"" Vimux mappings
nnoremap <leader>vp :VimuxPromptCommand<CR>
nnoremap <leader>vl :VimuxRunLastCommand<CR>
nnoremap <leader>vi :VimuxInspectRunner<CR>
nnoremap <leader>vz :VimuxZoomRunner<CR>
"" LanguageClient mappings
nnoremap <F5> :call LanguageClient_contextMenu()<CR>
nnoremap <leader>lh :call LanguageClient#textDocument_hover()<CR>
nnoremap <leader>ld :call LanguageClient#textDocument_definition()<CR>
nnoremap <leader>lr :call LanguageClient#textDocument_rename()<CR>
nnoremap <leader>lf :call LanguageClient_textDocument_documentSymbol()<CR>
"" Prettier mappings
nmap <Leader>py <Plug>(Prettier)

""" FUNCTIONS
" toggle preview window
function! TogglePreview()
  if (&completeopt =~ '.*preview.*')
    execute "set completeopt-=preview"
  else
    execute "set completeopt+=preview"
  endif
endfunction
" toggle between number and relativenumber
function! ToggleRelativeNumbers()
  if(&relativenumber == 1)
    set norelativenumber
    set number
  else
    set relativenumber
  endif
endfunc
" strips trailing whitespace at the end of files.
function! StripTrailingWhitespaces()
  " save last search & cursor position
  let _s=@/
  let l = line(".")
  let c = col(".")
  %s/\s\+$//e
  let @/=_s
  call cursor(l, c)
endfunction

""" PLUGINS
"" Indent guides options
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd ctermbg=NONE guibg=NONE
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=232 guibg=#080808
nnoremap <leader>ig :IndentGuidesToggle<CR>
"" Airline options
let g:airline_theme='monokai_tasty'
"let g:airline_theme='luna'
let g:airline_powerline_fonts = 1
let g:ale_linters = { 'javascript': ['eslint'] }
" set the filename section
let g:airline_section_c = '%t'
" set the line number section
let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])
" ale syntax checker status
let g:airline#extensions#ale#enabled = 1
"" CtrlP options
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|\_site|node_modules)$',
  \ 'file': '\v\.(exe|so|dll|class|png|jpg|jpeg)$',
\}
let g:ctrlp_max_files = 0
let g:ctrlp_working_path_mode = 'r'
"" Syntastic options
let g:syntastic_javascript_checkers = ['eslint']
"" JSX options
" allow JSX in normal JS files
let g:jsx_ext_required = 0
"" Ledger options
let g:ledger_align_at = 60
let g:ledger_decimal_sep = '.'
let g:ledger_default_commodity = 'MAD'
let g:ledger_commodity_before = 0
let g:ledger_commodity_sep = ' '
augroup ledger
  autocmd!
  autocmd FileType ledger set foldmethod=syntax
  autocmd FileType ledger nnoremap <c-d> "=strftime("%Y-%m-%d")<CR>P
  autocmd FileType ledger inoremap <c-d> <Esc>"=strftime("%Y-%m-%d")<CR>Pa
  autocmd FileType ledger inoremap <silent><s-Tab> <c-x><c-o>
  autocmd FileType ledger vnoremap <silent><buffer><TAB> :LedgerAlign<CR>
  autocmd FileType ledger inoremap <silent><buffer><c-a> <Esc>:call ledger#align_amount_at_cursor()<CR>
  autocmd FileType ledger noremap { ?^\d<CR>
  autocmd FileType ledger noremap } /^\d<CR>
  autocmd FileType ledger noremap <silent><buffer><c-t> :call ledger#transaction_state_toggle(line('.'), ' *?!')<CR>
  autocmd FileType ledger nnoremap <silent><buffer><localleader>d <Esc>:call ledger#transaction_date_set(line('.'), 'auxiliary')<CR>
augroup END
"" Emmet options
let g:user_emmet_settings = {
      \  'javascript.jsx' : {
      \      'extends' : 'jsx',
      \  },
      \}
"" Deoplete options
let g:deoplete#enable_at_startup = 1
" disable the candidates in Comment/String syntaxes.
call deoplete#custom#source('_',
      \ 'disabled_syntaxes', ['Comment', 'String'])
" sources
call deoplete#custom#option('sources', {
      \ '_': ['file'],
      \ 'html': ['file', 'LanguageClient'],
      \ 'css': ['file', 'LanguageClient'],
      \ 'javascript': ['file', 'LanguageClient'],
      \ 'javascript.jsx': ['file', 'LanguageClient'],
      \ 'typescript': ['file', 'LanguageClient'],
      \ 'typescript.jsx': ['file', 'LanguageClient'],
      \ 'python': ['file', 'LanguageClient'],
      \ })
" patterns
"call deoplete#custom#option('omni_patterns', {
		"\ 'java': '[^. *\t]\.\w*',
		"\})
"" LSP options
" automatically start language servers
let g:LanguageClient_autoStart = 1
" no diagnostics handling
let g:LanguageClient_diagnosticsEnable = 0
" required for operations modifying multiple buffers like rename.
set hidden
" servers
let g:LanguageClient_serverCommands = {
      \ 'html': ['html-languageserver', '--stdio'],
      \ 'css': ['css-languageserver', '--stdio'],
      \ 'javascript': ['/usr/local/bin/javascript-typescript-stdio'],
      \ 'javascript.jsx': ['/usr/local/bin/javascript-typescript-stdio'],
      \ 'typescript': ['/usr/local/bin/javascript-typescript-stdio'],
      \ 'typescript.jsx': ['/usr/local/bin/javascript-typescript-stdio'],
      \ 'python': ['/usr/local/bin/pyls'],
      \ }
"" Javacomplete2
" autocmd FileType java setlocal omnifunc=javacomplete#Complete
"" Supertab options
" setup completion chaining, omni then keyword
"autocmd FileType *
      "\ if &omnifunc != '' |
      "\   call SuperTabChain(&omnifunc, "<c-p>") |
      "\ endif
" set default to scroll down the list
let g:SuperTabDefaultCompletionType = "<c-n>"
" close the preview window when you're not using it
let g:SuperTabClosePreviewOnPopupClose = 1
"" Ultisnips options
let g:UltiSnipsExpandTrigger="<C-e>"
"" Prettier options
let g:prettier#autoformat = 0
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync
"" Fzf options
set rtp+=~/.fzf
let $FZF_DEFAULT_COMMAND = 'ag -g ""'
