# shell tools
cask "iterm2"
brew "tmux"
brew "zsh"

# vim tools
brew "neovim"
brew "ctags"

# search tools
brew "the_silver_searcher"

# keyboard tools
cask "karabiner-elements"

# languages
brew "node"
brew "nvm"
brew "python"
